name: dont_forget
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.14.1
  flutter_local_notifications: ^18.0.0
  flutter_timezone: ^3.0.1
  functional_widget_annotation: ^0.10.0
  intl: ^0.20.0
  shared_preferences: ^2.3.2
  timezone: ^0.10.0

dev_dependencies:
  build_runner: ^2.4.13
  functional_widget: ^0.10.2
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
