// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_vOcyKUWL0R7A-MqVx2LeD0vXa99Q9tg',
    appId: '1:934001225549:web:79ee320f4702b578121104',
    messagingSenderId: '934001225549',
    projectId: 'dontforgetdev-986d7',
    authDomain: 'dontforgetdev-986d7.firebaseapp.com',
    storageBucket: 'dontforgetdev-986d7.firebasestorage.app',
    measurementId: 'G-RL7Q7CTHWB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAs1VmAM4oQylJJ1z8QlScQ_wj_wALtjbE',
    appId: '1:934001225549:android:78c02577230a2ae0121104',
    messagingSenderId: '934001225549',
    projectId: 'dontforgetdev-986d7',
    storageBucket: 'dontforgetdev-986d7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCH9mAwAhhDao0mDCHCda8_5BcztJWbYL0',
    appId: '1:934001225549:ios:ab6da3f6965c7d01121104',
    messagingSenderId: '934001225549',
    projectId: 'dontforgetdev-986d7',
    storageBucket: 'dontforgetdev-986d7.firebasestorage.app',
    iosBundleId: 'com.example.dontForget',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCH9mAwAhhDao0mDCHCda8_5BcztJWbYL0',
    appId: '1:934001225549:ios:ab6da3f6965c7d01121104',
    messagingSenderId: '934001225549',
    projectId: 'dontforgetdev-986d7',
    storageBucket: 'dontforgetdev-986d7.firebasestorage.app',
    iosBundleId: 'com.example.dontForget',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA_vOcyKUWL0R7A-MqVx2LeD0vXa99Q9tg',
    appId: '1:934001225549:web:51cec73e6f63ca1c121104',
    messagingSenderId: '934001225549',
    projectId: 'dontforgetdev-986d7',
    authDomain: 'dontforgetdev-986d7.firebaseapp.com',
    storageBucket: 'dontforgetdev-986d7.firebasestorage.app',
    measurementId: 'G-ZD4YQKEDJR',
  );
}
